import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dental App",
  description: "Generated by Sumeth Vindunu",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      variables: {
        colorBackground: '#111111',
        colorForeground: '#eeeeee',
        colorPrimary: '#ffe0c2',
        colorPrimaryForeground: '#081a1b',
        colorInput: '#222222',
        colorInputForeground: '#eeeeee',
        colorMuted: '#222222',
        colorMutedForeground: '#b4b4b4',
        colorNeutral: '#ffffff',
      }
    }}
    >
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
      >
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </ClerkProvider>
  );
}
